# Autogenerated file
def render(*a, **d):
    # Autogenerated file
    def render1(*a, **d):
        yield """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <link rel=\"stylesheet\" href=\"style.css\">
    <title>GlowNet Dome</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href=\"/\">Home</a></li>
                <li><a href=\"/logs\">Logs</a></li>
                <li><a href=\"/updatedome\">Control</a></li>
            </ul>
        </nav>
        <h1>Welcome to your GlowNet Dome</h1>
    </header>

"""
    yield from render1()
    yield """<div id=\"intro\">
    Use the navigation at the top of this page to administer your GlowNet Dome.
</div>
"""
# Autogenerated file
    def render2(*a, **d):
        yield """    <footer>
        <p>&copy; 2023 GlowNet. All rights reserved.</p>
    </footer>
</body>
</html>"""
    yield from render2()
