# Autogenerated file
def render(files):
    yield """<!DOCTYPE html>
<html>
<head>
<title>GlowNet Dome</title>
<style>
    table, th, td """
    yield """{
      border:1px solid black;
    }
</style>
</head>
<body>
    <h1>GlowNet Dome</h1>
    <h2>Log Files</h2>
    <table>
        """
    for file in files:
        yield """        <tr>
            <td><a href='/logs/"""
        yield str(file)
        yield """'>"""
        yield str(file)
        yield """</a></td>
        </tr>
        """
    yield """    </table>
</body>
</html>"""
