# Autogenerated file
def render(*a, **d):
    yield """    /* Reset some default styles */
body, h1, h2, h3, p, ul """
    yield """{
    margin: 0;
    padding: 0;
}

body """
    yield """{
    font-family: Arial, sans-serif;
    background-color: #f9f9f9;
}

/* Header */
header """
    yield """{
    background-color: #333;
    color: #fff;
    padding: 20px 0;
    text-align: center;
}

nav """
    yield """{
    display: flex;
    align-items: center;
    justify-content: space-between;
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
}

nav img """
    yield """{
    height: 60px;
}

nav ul """
    yield """{
    list-style: none;
    display: flex;
}

nav ul li """
    yield """{
    margin-right: 20px;
}

nav ul li a """
    yield """{
    color: #fff;
    text-decoration: none;
    transition: color 0.3s;
}

nav ul li a:hover """
    yield """{
    color: #ff9900;
}

/* Hero Section */
#intro """
    yield """{
    color: #000000;
    text-align: center;
    padding: 100px 0;
    width: 40%;
    margin: auto;
    border: 3pm solid green;
}

#intro h2 """
    yield """{
    font-size: 36px;
    margin-bottom: 20px;
}

table, th, td """
    yield """{
      border:1px solid black;
    }

#logTable """
    yield """{
    margin-bottom: 50px;
}

.maindiv"""
    yield """{
    padding-left: 20px;
    padding-top: 20px;
}

.leftColumn"""
    yield """{
            text-align: right;
        }"""
